version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_fastapp
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: clientesdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: app_pass123
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_fastapp
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_apache_fastapp
    depends_on:
      - db
    ports:
      - "80:80"
    restart: always

volumes:
  db_data:
